---
title: Java异常处理机制的使用
date: 2025-07-21 10:55:54
tags:
---

一般在代码中Java的异常处理机制使用场景是比较多的，本文围绕Java异常处理机制怎么使用展开

# 出现异常后只记录日志

当程序出现异常，并且捕获后不抛出异常只记录日志，那么整个程序是不断中断的

```java
@SpringBootTest
@Slf4j
class WorkTestApplicationTests {
    public void ex(){
        try {
            log.info("准备出现异常====");
            int i = 1/0;//模拟出现异常
        } catch (Exception e) {
            //e.printStackTrace();//使用输出堆栈信息可以显示更完整的错误信息
            log.error("异常：{}",e.getMessage());
        }
    }

    @Test
    public void testCompare() throws InterruptedException {
        ex();

        //模拟程序后续运行
        while(true){
            Thread.sleep(1000);
            System.out.println("程序运行中===");
        }
    }
}
```



输出结果

```
2025-07-21 11:04:51.580  INFO 22488 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 11:04:51.580 ERROR 22488 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero
程序运行中===
```



# 出现异常后直接中断程序

该try-catch的处理方式结果和没有try-catch处理的结果都是一样的，异常会直接中断程序然后退出

```java
@SpringBootTest
@Slf4j
class WorkTestApplicationTests {
    public void ex(){
        try {
            log.info("准备出现异常====");
            int i= 1/0;
        } catch (Exception e) {
            //e.printStackTrace();//使用输出堆栈信息可以显示更完整的错误信息
            log.error("异常：{}",e.getMessage());
            throw new RuntimeException("异常："+e.getMessage());
        }
    }

    @Test
    public void testCompare() throws InterruptedException {
        ex();

        //模拟程序后续运行
        while(true){
            Thread.sleep(1000);
            System.out.println("程序运行中===");
        }
    }
}
```



```
2025-07-21 14:13:45.728  INFO 9636 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 14:13:45.729 ERROR 9636 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero

java.lang.RuntimeException: 异常：/ by zero

	at com.sky.work_test.WorkTestApplicationTests.ex(WorkTestApplicationTests.java:23)
	at com.sky.work_test.WorkTestApplicationTests.testCompare(WorkTestApplicationTests.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


进程已结束，退出代码为 -1

```







# 出现异常不影响循环处理

想要让当前数据的异常不影响下一条数据的执行，那么就使用捕获异常输出日志的方式

```java
@SpringBootTest
@Slf4j
class WorkTestApplicationTests {
    public void ex(){
        for(int n=0;n<5;n++){
            try {
                //业务逻辑...
                log.info("准备出现异常====");
                int i= 1/0;
            } catch (Exception e) {
                //e.printStackTrace();//使用输出堆栈信息可以显示更完整的错误信息
                log.error("异常：{}",e.getMessage());
            }
        }
    }

    @Test
    public void testCompare() throws InterruptedException {
        ex();

        //模拟程序后续运行
        while(true){
            Thread.sleep(1000);
            System.out.println("程序运行中===");
        }
    }
}
```



```
2025-07-21 11:10:52.088  INFO 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 11:10:52.088 ERROR 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero
2025-07-21 11:10:52.089  INFO 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 11:10:52.089 ERROR 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero
2025-07-21 11:10:52.089  INFO 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 11:10:52.089 ERROR 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero
2025-07-21 11:10:52.090  INFO 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 11:10:52.090 ERROR 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero
2025-07-21 11:10:52.090  INFO 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 11:10:52.090 ERROR 24888 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero
程序运行中===
```



# 出现异常中断循环处理程序

想要让循环中如果出现异常就立马退出循环处理，则就throw抛出异常，将异常交给调用者处理

```java
@SpringBootTest
@Slf4j
class WorkTestApplicationTests {
    public void ex(){
        for(int n=0;n<5;n++){
            try {
                log.info("准备出现异常====");
                int i= 1/0;
            } catch (Exception e) {
                //e.printStackTrace();//使用输出堆栈信息可以显示更完整的错误信息
                log.error("异常：{}",e.getMessage());
                throw new RuntimeException("异常："+e.getMessage());//该异常会抛给调用者
            }
        }
    }

    @Test
    public void testCompare() throws InterruptedException {
        try{
            ex();
        }
        catch (Exception e){
            //ex()方法的异常到了该处，为了使得程序还能够执行后面的流程，所以需要捕获异常
            log.error("程序发生异常，在此处处理:"+e.getMessage());
        }
        

        //模拟程序后续运行
        while(true){
            Thread.sleep(1000);
            System.out.println("程序运行中===");
        }
    }
}
```



```
2025-07-21 11:21:15.285  INFO 25780 --- [           main] c.s.work_test.WorkTestApplicationTests   : 准备出现异常====
2025-07-21 11:21:15.285 ERROR 25780 --- [           main] c.s.work_test.WorkTestApplicationTests   : 异常：/ by zero
2025-07-21 11:21:15.286 ERROR 25780 --- [           main] c.s.work_test.WorkTestApplicationTests   : 程序发生异常，在此处处理:异常：/ by zero
程序运行中===
```

